"""create migration

Revision ID: d068a1c88e37
Revises: 33acb08eb844
Create Date: 2024-03-27 21:17:38.745105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd068a1c88e37'
down_revision = '33acb08eb844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('stock_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('money_to_buy', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('algorithm_start_time', sa.String(), nullable=False))
    op.add_column('order', sa.Column('algorithm_end_time', sa.String(), nullable=False))
    op.add_column('order', sa.Column('volume', sa.Integer(), nullable=False))
    op.drop_column('order', 'algorithm_time')
    op.drop_column('order', 'ticker')
    op.drop_column('order', 'target_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('target_amount', sa.VARCHAR(), nullable=False))
    op.add_column('order', sa.Column('ticker', sa.VARCHAR(), nullable=False))
    op.add_column('order', sa.Column('algorithm_time', sa.VARCHAR(), nullable=False))
    op.drop_column('order', 'volume')
    op.drop_column('order', 'algorithm_end_time')
    op.drop_column('order', 'algorithm_start_time')
    op.drop_column('order', 'money_to_buy')
    op.drop_column('order', 'stock_id')
    # ### end Alembic commands ###
